spring.application.name=BeerProject
server.port=8080
spring.messages.basename=messages
spring.web.locale=ca
spring.web.locale-resolver=fixed

#PROFILES
#spring.profiles.active= collections
#spring.profiles.active= dev, jdbc
#spring.profiles.active= prod, jpa
spring.profiles.active= prod, jpa_rep

