spring.application.name=BeerProject
server.port=8080
spring.messages.basename=templates/messages

#PROFILES
spring.profiles.active= collections
#spring.profiles.active= dev, jdbc
#spring.profiles.active= prod, jpa
#spring.profiles.active= prod, jpa_rep

