spring.datasource.url=jdbc:h2:file:./db/beerdb
spring.datasource.username=sa
spring.datasource.password=sa
spring.sql.init.mode= always
spring.h2.console.enabled=true

spring.sql.init.schema-locations=classpath:schema_dev.sql
spring.sql.init.data-locations=classpath:data_dev.sql
