spring.application.name=BeerProject
server.port=8080
spring.messages.basename=templates/messages

spring.datasource.url=jdbc:h2:file:./db/beerdb
spring.datasource.username=sa
spring.datasource.password=sa
spring.sql.init.mode= always

