INSERT INTO PUBLIC.BEER (NAME, ABV, PLATO, STYLE, QUANTITY, STOCK, CONTAINER, BREWERY, PRICE) VALUES ('Puck v6', 5.5, 12, 'Fruit Sour', 'BELGIAN', 120, 'CAN', 'Kaapse', 2.50);
INSERT INTO PUBLIC.BEER (NAME, ABV, PLATO, STYLE, QUANTITY, STOCK, CONTAINER, BREWERY, PRICE) VALUES ('Swiped Out', 8.8, 19, 'Double IPA', 'BOMBER', 96, 'BOTTLE', 'Frau Gruber', 3.80);
INSERT INTO PUBLIC.BEER (NAME, ABV, PLATO, STYLE, QUANTITY, STOCK, CONTAINER, BREWERY, PRICE) VALUES ('Phuture 2', 6, 15, 'IPA', 'STUBBY', 108, 'CAN', 'Cloudwater', 3.55);
INSERT INTO PUBLIC.BEER (NAME, ABV, PLATO, STYLE, QUANTITY, STOCK, CONTAINER, BREWERY, PRICE) VALUES ('The Dreamer', 6.6, 16, 'West Coast IPA', 'TALLBOY', 4, 'KEG', 'Oddity', 110.45);
